remote_theme: minima

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minima:
  header_pages:
    - index.md
    - 2026-agenda.md
    - things-to-do.md 
    
title: "W5133 Multi-State Project"


