remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "W5133 Multi-State Project"
# Pages to include in the top navigation bar
header_pages:
  - index
  - annual-reports.html
  - 2025-agenda.html
  - 2024-agenda.html
  - 2023-agenda.html
  - 2022-agenda.html


# Define custom navigation links




#old code
#nav:
#  - Home: 'index.md'
#  - Annual Reports: 'annual-reports.md'
  
