

# Site settings
title: W5133 Research Group
email: contact@w5133.github.io
description: >- # This is a YAML multiline string. Adjust accordingly.
  The W5133 Research Group focuses on innovative research in land use, non-market valuation and recreation on public lands.
  Join us for regular meetings and explore our annual reports.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://w5133.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  meetings:
    output: true
    permalink: /meetings/:name/
  annual_reports:
    output: true
    permalink: /annual-reports/:name/

# Permalinks
permalink: /:categories/:year/:month/:day/:title:output_ext

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      author: "Your Default Author Name" # Replace with the name of a frequent author or the group itself.

# SEO Tags
title: W5133 Research Group
description: "Advancing computational science through collaborative research."
author: W5133 Research Group

# Social Media (example placeholders, replace with actual usernames)
social:
  twitter: W5133Group
  facebook: W5133Group
  github: W5133

# Google Analytics (replace UA-XXXXX-Y with your actual tracking ID)
google_analytics: UA-XXXXX-Y

# Comments - Assuming you're using Disqus for comments
disqus:
  shortname: w5133-research-group

# Optional Features
# Localization settings, plugins configurations, etc., based on your needs.