remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Pages to include in the top navigation bar
header_pages:
  - index.md
  - annual-reports.md
  - 2025-agenda.md
  - 2024-agenda.md
  - 2023-agenda.md
  - 2022-agenda.md
  - contact.md

# Define custom navigation links




#old code
#nav:
#  - Home: 'index.md'
#  - Annual Reports: 'annual-reports.md'
  
